repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # UV version.
    rev: 0.5.10
    hooks:
      # Compile requirements.
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
