[project]
name = "recipes-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "lancedb>=0.21.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "playwright>=1.51.0",
    "pre-commit>=4.2.0",
]
